DEFINE	CSVLoader org.apache.pig.piggybank.storage.CSVLoader;

RECORDS = load '/Users/andang/IdeaProjects/test_result/project/part-r-00000' USING CSVLoader AS
          (heroId:int, itemSet:chararray, kills:int, deaths:int);

HERO_ITEM_SETS = FILTER RECORDS BY heroId == 11;
ITEM_SET_TO_PERFORMANCE = FOREACH HERO_ITEM_SETS GENERATE itemSet, kills/deaths as performance;
GROUPED_BY_ITEM_SET = GROUP ITEM_SET_TO_PERFORMANCE BY itemSet;
GROUPED_BY_ITEM_SET_AVG_PERFORMANCE = FOREACH GROUPED_BY_ITEM_SET GENERATE ITEM_SET_TO_PERFORMANCE.itemSet, AVG(ITEM_SET_TO_PERFORMANCE.performance) as avgPerformance;
SORTED_GROUPED_BY_ITEM_SET_AVG_PERFORMANCE = ORDER GROUPED_BY_ITEM_SET_AVG_PERFORMANCE BY avgPerformance DESC ;
SORTED_GROUPED_BY_ITEM_SET_AVG_PERFORMANCE_TOP_10 = LIMIT SORTED_GROUPED_BY_ITEM_SET_AVG_PERFORMANCE 10;
--
--SORTED_HERO_COUNTS = ORDER HERO_COUNTS BY heroCount DESC ;
--SORTED_HERO_COUNTS_TOP_10 = LIMIT SORTED_HERO_COUNTS 10;
--TOP_10_HEROES = FOREACH SORTED_HERO_COUNTS_TOP_10 GENERATE group;
store SORTED_GROUPED_BY_ITEM_SET_AVG_PERFORMANCE_TOP_10 into '/Users/andang/IdeaProjects/test_result/project_pig_2/';
